# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kindex(object):
    def setupUi(self, kindex):
        kindex.setObjectName("kindex")
        kindex.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(kindex)
        self.centralwidget.setObjectName("centralwidget")
        self.hosgeldiniz = QtWidgets.QLabel(self.centralwidget)
        self.hosgeldiniz.setGeometry(QtCore.QRect(20, 20, 751, 41))
        self.hosgeldiniz.setStyleSheet("font: 22pt \"MV Boli\";")
        self.hosgeldiniz.setObjectName("hosgeldiniz")
        self.lbl_kg = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_kg.setGeometry(QtCore.QRect(160, 120, 221, 41))
        self.lbl_kg.setObjectName("lbl_kg")
        self.kg = QtWidgets.QLabel(self.centralwidget)
        self.kg.setGeometry(QtCore.QRect(30, 120, 121, 31))
        self.kg.setStyleSheet("font: 20pt \"MV Boli\";")
        self.kg.setObjectName("kg")
        self.boy = QtWidgets.QLabel(self.centralwidget)
        self.boy.setGeometry(QtCore.QRect(400, 120, 131, 41))
        self.boy.setStyleSheet("font: 20pt \"MV Boli\";")
        self.boy.setObjectName("boy")
        self.lbl_boy = QtWidgets.QLineEdit(self.centralwidget)
        self.lbl_boy.setGeometry(QtCore.QRect(540, 120, 221, 41))
        self.lbl_boy.setObjectName("lbl_boy")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(30, 240, 721, 121))
        self.sonuc.setStyleSheet("font: 20pt \"MV Boli\";")
        self.sonuc.setObjectName("sonuc")
        self.hesapla = QtWidgets.QPushButton(self.centralwidget)
        self.hesapla.setGeometry(QtCore.QRect(640, 190, 121, 51))
        self.hesapla.setStyleSheet("font: 20pt \"MV Boli\";")
        self.hesapla.setObjectName("hesapla")
        self.temizle = QtWidgets.QPushButton(self.centralwidget)
        self.temizle.setGeometry(QtCore.QRect(500, 190, 121, 51))
        self.temizle.setStyleSheet("font: 20pt \"MV Boli\";")
        self.temizle.setObjectName("temizle")
        self.lbl_state = QtWidgets.QLabel(self.centralwidget)
        self.lbl_state.setGeometry(QtCore.QRect(380, 430, 391, 71))
        self.lbl_state.setStyleSheet("font: 20pt \"MV Boli\";")
        self.lbl_state.setObjectName("lbl_state")
        kindex.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kindex)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        kindex.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kindex)
        self.statusbar.setObjectName("statusbar")
        kindex.setStatusBar(self.statusbar)

        self.retranslateUi(kindex)
        QtCore.QMetaObject.connectSlotsByName(kindex)

    def retranslateUi(self, kindex):
        _translate = QtCore.QCoreApplication.translate
        kindex.setWindowTitle(_translate("kindex", "MainWindow"))
        self.hosgeldiniz.setText(_translate("kindex", "Vücut kitle indexi hesaplama programımıza hoşgeldiniz!"))
        self.kg.setText(_translate("kindex", "Kilonuz :"))
        self.boy.setText(_translate("kindex", "Boyunuz :"))
        self.sonuc.setText(_translate("kindex", "Sonuç :"))
        self.hesapla.setText(_translate("kindex", "Hesapla"))
        self.temizle.setText(_translate("kindex", "Temizle"))
        self.lbl_state.setText(_translate("kindex", "Durum :"))
