# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 481, 61))
        self.label.setStyleSheet("font: 75 14pt \"Myanmar Text\";")
        self.label.setObjectName("label")
        self.ogr_ekle_button = QtWidgets.QPushButton(self.centralwidget)
        self.ogr_ekle_button.setGeometry(QtCore.QRect(130, 160, 121, 51))
        self.ogr_ekle_button.setObjectName("ogr_ekle_button")
        self.kitap_ver_input = QtWidgets.QPushButton(self.centralwidget)
        self.kitap_ver_input.setGeometry(QtCore.QRect(330, 160, 121, 51))
        self.kitap_ver_input.setObjectName("kitap_ver_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 130, 131, 21))
        self.label_2.setStyleSheet("font: 75 14pt \"Myanmar Text\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 130, 91, 21))
        self.label_3.setStyleSheet("font: 75 14pt \"Myanmar Text\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "(BASİC) KÜTÜPHANE OTOMASYONUNA HOŞ GELDİNİZ!"))
        self.ogr_ekle_button.setText(_translate("MainWindow", "öğrenci ekle"))
        self.kitap_ver_input.setText(_translate("MainWindow", "kitap ver"))
        self.label_2.setText(_translate("MainWindow", "ÖĞRENCİ EKLE"))
        self.label_3.setText(_translate("MainWindow", "KITAP VER"))
