# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class KitapVer(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 31, 31))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 81, 21))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.kitap_adi_input = QtWidgets.QLineEdit(self.centralwidget)
        self.kitap_adi_input.setGeometry(QtCore.QRect(110, 100, 241, 41))
        self.kitap_adi_input.setObjectName("kitap_adi_input")
        self.ad_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_input.setGeometry(QtCore.QRect(110, 40, 241, 41))
        self.ad_input.setObjectName("ad_input")
        self.kitab_ver_input = QtWidgets.QPushButton(self.centralwidget)
        self.kitab_ver_input.setGeometry(QtCore.QRect(250, 160, 101, 41))
        self.kitab_ver_input.setObjectName("kitab_ver_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 41, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.ogr_no_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ogr_no_input.setGeometry(QtCore.QRect(110, 160, 61, 41))
        self.ogr_no_input.setObjectName("ogr_no_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ad : "))
        self.label_2.setText(_translate("MainWindow", "Kitap Adı :"))
        self.kitab_ver_input.setText(_translate("MainWindow", "kitabı ver"))
        self.label_3.setText(_translate("MainWindow", "No :"))
