# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class OgrenciEkle(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ogr_ad_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ogr_ad_input.setGeometry(QtCore.QRect(150, 40, 231, 41))
        self.ogr_ad_input.setObjectName("ogr_ad_input")
        self.ogr_soyad_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ogr_soyad_input.setGeometry(QtCore.QRect(150, 100, 231, 41))
        self.ogr_soyad_input.setObjectName("ogr_soyad_input")
        self.ogr_no_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ogr_no_input.setGeometry(QtCore.QRect(320, 160, 61, 41))
        self.ogr_no_input.setObjectName("ogr_no_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 91, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 170, 41, 21))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 91, 21))
        self.label_2.setObjectName("label_2")
        self.ogr_save_button = QtWidgets.QPushButton(self.centralwidget)
        self.ogr_save_button.setGeometry(QtCore.QRect(260, 270, 131, 51))
        self.ogr_save_button.setObjectName("ogr_save_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Öğrenci adı :"))
        self.label_3.setText(_translate("MainWindow", "No:"))
        self.label_2.setText(_translate("MainWindow", "Öğrenci soyadı :"))
        self.ogr_save_button.setText(_translate("MainWindow", "Öğrenciyi Kaydet"))
